version: '3'
services:
  web:
    build:
      contenxt: .
      args:
        NODE_ENV: production
    ports:
    - "8080:8080"
    environment:
    - NODE_ENV=uat
    container_name: fe-docker-compose
    volumes:
    - "./src:/opt/app-root/src"